[package]
name = "fachprojekt2k19"
version = "0.1.0"
authors = ["Conturing <13372078+Conturing@users.noreply.github.com>"]
edition = "2018"

[dependencies]
bio = "*"
bv = { version = "0.10", features = ["serde"]} 
num-traits = "*"
